language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install pep8 --use-mirrors
before_script:
    - "pep8 --exclude=migrations apps"
script:
    - echo "Should do more stuff here"
