language: python
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99.0"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x2000x16"
install:
    - pip install -r requirements.txt
    - pip install pep8
    - pip install coveralls
env:
    global:
        - build_on_travis=true
sudo: false
before_script:
    - "pep8 --exclude=migrations --config=.pep8 apps"
    - "python manage.py makemigrations"
    - "python manage.py migrate"
script:
    - "./manage.py test"
after_success:
  - coveralls
