language: python
python:
    - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
    - pip install -r requirements.txt
    - pip install pep8 --use-mirrors
env:
    global:
        - build_on_travis=true
sudo:
    - false
before_script:
    - "pep8 --exclude=migrations --config=.pep8 apps"
script:
    - "./manage.py test apps.web_fe.tests -v 2"

